# Generated by Django 6.0.7 on 2026-07-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=50)),
                ('audience', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['destination', 'audience'], name='landing_out_destina_0f3318_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audience', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['audience', 'timestamp'], name='landing_vis_audienc_61d39d_idx')],
            },
        ),
    ]
